name: Deploy to DO
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete latest image
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: geo-front
          dockerfile: Dockerfile

      - uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          user: root
          pass: ${{ secrets.DO_PASS }}
          run: |
            cd ~/app
            echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
            docker-compose stop
            docker-compose rm --force front-end
            docker rmi docker.pkg.github.com/presto-agency/geo/geo-front:latest
            docker pull https://docker.pkg.github.com/presto-agency/geo/geo-front:latest
            docker-compose up -d --build
            docker logout https://docker.pkg.github.com
